### PR TITLE
Fixed a crash in iOS Example

### PR DESCRIPTION
**Pull request by talzag**
The `present` method of `CDE.m` was causing the app to crash if a user tried to invoke this method twice in a row.

I've also added a template for an action extension to the app. I don't know if it's possible, but it would be cool to inspect the Core Data data in other apps (as long as they pass a managed object to the extension context). Kind of like this https://itunes.apple.com/us/app/view-source-html-javascript/id917660039?mt=8 , but for Core Data entities instead of HTML/CSS/JS. If that's something that can't be done or isn't feasible, that extension can be removed.

### CODE REVIEW

**Comment by ChristianKienle** [comment]
I have to look into this in more detail... Tomorrow I have a bit of time on the train. Thanks for the pull request. It is certainly a really cool idea.

**Comment by ChristianKienle** [comment]
Hi there!

Sorry for not getting back to your PR in ages. I had a lot of things to do. Development of Core Data Editor is resuming so I will try to merge your PR shortly. Again - sorry. Friends again? :)

**Comment by talzag** [comment]
Hey @ChristianKienle no problem, glad to see you're back 😃. I'm going to close this PR & create a new one from my latest fork. I think my original idea for the app extension isn't possible, so I don't think it's a loss to abandon this request.

**Comment by ChristianKienle** [comment]
@talzag thank you very much. Yesterday I have released Core Data Editor 5.2

https://github.com/ChristianKienle/Core-Data-Editor/releases/tag/5.2

Core Data Editor now has a develop and master branch. I suggest you branch from develop and go from there. Thanks in advance.

**Pull request closed without merging**
