### PR TITLE
Copy CoreDataEditor to Applications on every run

### PR DESCRIPTION
**Pull request by RahulKatariya**

### CODE REVIEW

**Comment by ChristianKienle** [comment]
Thanks! May I ask why you want Core Data Editor to be copied to /Applications?

**Comment by RahulKatariya** [comment]
Hi, It is very handy to run Core-Data-Editor directly from the Applications rather than opening the project and run it. I thought it will help people too.

**Comment by ChristianKienle** [comment]
I think it would be even easier for people to just download Core Data Editor as an App. Well let me checkout your PR real quick... Btw: I have just merge a big PR to develop... it requires macOS 10.12 though...

**Comment by RahulKatariya** [comment]
I was searching for the link to download Core Data Editor App but couldn't find it.

**Comment by ChristianKienle** [comment]
https://github.com/ChristianKienle/Core-Data-Editor/releases/tag/5.2

**Comment by RahulKatariya** [comment]
Thanks 👍🏻. It would be great to see a brew cask of Core Data Editor App sometime.

**Pull request closed without merging**
